# Model parameters
model:
  input_dim: 3
  hidden_dim: 128 # feature dimension for point sampler and face classifier (as per paper)
  edge_hidden_dim: 64 # feature dimension for edge predictor (as per paper)
  num_layers: 3 # number of convolutional layers (as per paper)
  k: 15 # number of neighbors for graph construction (as per paper)
  edge_k: 15 # number of neighbors for edge features (as per paper)
  target_ratio: 0.5 # mesh simplification ratio

# Training parameters
training:
  learning_rate: 1.0e-5
  weight_decay: 0.99 # weight decay per epoch (as per paper)
  batch_size: 2
  num_epochs: 20 # total training epochs
  early_stopping_patience: 15 # epochs before early stopping
  checkpoint_dir: data/checkpoints # model save directory

# Data parameters
data:
  data_dir: data/processed
  val_split: 0.2

# Loss weights
loss:
  lambda_c: 1.0 # chamfer distance weight
  lambda_e: 1.0 # edge preservation weight
  lambda_o: 1.0 # normal consistency weight
